# -*- coding: utf-8 -*-
"""Jewelry_Data_Analysis_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVhu34uypGj_9isfbgS0uBwfw0EvpgO8

1. Cài đặt & import thư viện
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error, r2_score, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (9, 5)
np.random.seed(42)

"""2. Nạp dữ liệu & Data Cleaning"""

from google.colab import files
uploaded = files.upload()

CSV_PATH = "trang_suc_processed_full.csv"  # đổi lại đường dẫn nếu cần
df = pd.read_csv(CSV_PATH)
print("Kích thước dữ liệu:", df.shape)
df.head()

# --- Kiểm tra Data Cleaning ---
print("Số giá trị thiếu theo từng cột:")
print(df.isnull().sum())
print("\nSố bản ghi trùng lặp (toàn bộ dòng):", df.duplicated().sum())
print("Số bản ghi trùng lặp theo customer_id:", df.duplicated(subset=['customer_id']).sum())

def iqr_outliers(s):
    q1, q3 = s.quantile(.25), s.quantile(.75)
    iqr = q3 - q1
    lo, hi = q1 - 1.5*iqr, q3 + 1.5*iqr
    return ((s < lo) | (s > hi)).sum()

print("\nSố ngoại lệ (IQR) - purchase_amount_vnd:", iqr_outliers(df['purchase_amount_vnd']))
print("Số ngoại lệ (IQR) - weight_grams:", iqr_outliers(df['weight_grams']))
print("Số ngoại lệ (IQR) - previous_purchases:", iqr_outliers(df['previous_purchases']))

"""3. Xây dựng biến kỹ thuật (Feature Engineering)"""

# --- clv_est_vnd: điều chỉnh monetary_est_vnd theo review_rating và membership_status ---
rating_factor = 1 + (df['review_rating'] - 3.5) * 0.06
member_factor = np.where(df['membership_status'] == 'Có', 1.15, 0.95)
df['clv_est_vnd'] = (df['monetary_est_vnd'] * rating_factor * member_factor).round(0)

# --- next_period_spend_est_vnd: suy ra từ purchase_amount & tần suất mua ước tính, có nhiễu ngẫu nhiên ---
implied_freq = (30 / df['recency_proxy_days'].replace(0, 1)).clip(upper=3)
noise = np.random.normal(1.0, 0.18, size=len(df))
df['next_period_spend_est_vnd'] = (df['purchase_amount_vnd'] * implied_freq * noise).round(0)

# --- churn: nhãn rule-based ---
score = np.zeros(len(df))
score += df['frequency_of_purchases'].isin(['Hàng năm', 'Nửa năm một lần']).astype(int) * 2
score += (df['membership_status'] == 'Không').astype(int)
score += (df['review_rating'] < 3.5).astype(int)
score += (df['promo_code_used'] == 'Không').astype(int)
score += (df['discount_applied'] == 'Không').astype(int)
score -= df['frequency_of_purchases'].isin(['Hàng tuần', 'Hai tuần một lần']).astype(int)
rand_noise = np.random.normal(0, 0.9, size=len(df))
df['churn'] = ((score + rand_noise) >= 4.2).astype(int)

print("Tỷ lệ churn:", round(df['churn'].mean()*100, 1), "%")
df[['clv_est_vnd', 'next_period_spend_est_vnd', 'churn']].describe()

"""4. Phân tích khám phá dữ liệu (EDA)"""

num_cols = ['age','weight_grams','purchase_amount_vnd','previous_purchases','review_rating','monetary_est_vnd','clv_est_vnd']
df[num_cols].describe().T

# Hình 2: phân phối các biến định lượng chính
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
sns.histplot(df['age'], kde=True, ax=axes[0,0]); axes[0,0].set_title("Phân phối độ tuổi khách hàng")
sns.histplot(df['purchase_amount_vnd']/1e6, kde=True, ax=axes[0,1]); axes[0,1].set_title("Phân phối giá trị đơn hàng (triệu VND)")
sns.histplot(df['previous_purchases'], kde=True, ax=axes[1,0]); axes[1,0].set_title("Phân phối số lần mua trước đó")
sns.histplot(df['review_rating'], kde=True, ax=axes[1,1]); axes[1,1].set_title("Phân phối điểm đánh giá")
plt.tight_layout(); plt.show()

# Hình 3: ma trận tương quan
corr_cols = ['age','weight_grams','purchase_amount_vnd','previous_purchases','review_rating','recency_proxy_days','monetary_est_vnd','clv_est_vnd']
corr = df[corr_cols].corr()
plt.figure(figsize=(8, 6.5))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="YlOrBr")
plt.title("Ma trận tương quan giữa các biến hành vi khách hàng")
plt.tight_layout(); plt.show()

# Hình 4: giá trị đơn hàng trung bình theo danh mục & dịp mua
cat_avg = df.groupby('jewelry_category')['purchase_amount_vnd'].mean().sort_values(ascending=False)
occasion_avg = df.groupby('occasion')['purchase_amount_vnd'].mean().sort_values(ascending=False)

fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
(cat_avg/1e6).plot(kind='bar', ax=axes[0], color="#b08d57")
axes[0].set_title("Giá trị đơn hàng TB theo danh mục trang sức (triệu VND)"); axes[0].tick_params(axis='x', rotation=35)
(occasion_avg/1e6).plot(kind='bar', ax=axes[1], color="#8e6b3f")
axes[1].set_title("Giá trị đơn hàng TB theo dịp mua (triệu VND)"); axes[1].tick_params(axis='x', rotation=35)
plt.tight_layout(); plt.show()

print(cat_avg.round(0))
print(occasion_avg.round(0))

"""5. Dashboard tổng quan khách hàng"""

total_customers = len(df)
total_monetary = df['monetary_est_vnd'].sum()
avg_clv = df['clv_est_vnd'].mean()
churn_rate = df['churn'].mean()
churn_by_region = df.groupby('region')['churn'].mean().sort_index()
gender_spend_share = df.groupby('gender')['monetary_est_vnd'].sum()
gender_spend_share = gender_spend_share / gender_spend_share.sum() * 100
membership_rate = (df['membership_status'] == 'Có').mean()

print(f"Tổng khách hàng: {total_customers:,}")
print(f"Tổng chi tiêu ước tính: {total_monetary/1e9:.1f} tỷ VND")
print(f"CLV trung bình: {avg_clv/1e6:.1f} triệu VND/khách")
print(f"Tỷ lệ churn: {churn_rate*100:.1f}%")
print(f"Tỷ lệ đăng ký thành viên: {membership_rate*100:.1f}%")
print("\nTỷ lệ churn theo miền:\n", (churn_by_region*100).round(1))
print("\nCơ cấu chi tiêu theo giới tính (%):\n", gender_spend_share.round(1))

# Dashboard: KPI + churn theo miền + cơ cấu giới tính + phân phối rating
fig, axes = plt.subplots(2, 2, figsize=(12, 9))
kpi_text = (f"Tổng KH: {total_customers:,}\n"
            f"Tổng chi tiêu ước tính: {total_monetary/1e9:.1f} tỷ VND\n"
            f"CLV TB: {avg_clv/1e6:.1f} triệu VND\n"
            f"Tỷ lệ churn: {churn_rate*100:.1f}%")
axes[0,0].axis('off'); axes[0,0].text(0.05, 0.5, kpi_text, fontsize=14, va='center'); axes[0,0].set_title("KPI tổng quan")
churn_by_region.plot(kind='bar', ax=axes[0,1], color="#a15c38"); axes[0,1].set_title("Tỷ lệ churn theo miền")
gender_spend_share.plot(kind='pie', ax=axes[1,0], autopct='%1.1f%%'); axes[1,0].set_ylabel(""); axes[1,0].set_title("Cơ cấu chi tiêu theo giới tính")
sns.histplot(df['review_rating'], bins=10, ax=axes[1,1]); axes[1,1].set_title("Phân phối điểm đánh giá")
plt.tight_layout(); plt.show()

# Dashboard: hành vi & dịch vụ
churn_by_membership = df.groupby('membership_status')['churn'].mean()
churn_by_discount = df.groupby('discount_applied')['churn'].mean()

fig, axes = plt.subplots(2, 2, figsize=(12, 9))
churn_by_membership.plot(kind='bar', ax=axes[0,0], color="#8e6b3f"); axes[0,0].set_title("Tỷ lệ churn theo tình trạng thành viên")
churn_by_discount.plot(kind='bar', ax=axes[0,1], color="#a15c38"); axes[0,1].set_title("Tỷ lệ churn theo áp dụng giảm giá")
df['payment_method'].value_counts().plot(kind='bar', ax=axes[1,0], color="#c9a86a"); axes[1,0].set_title("Phương thức thanh toán"); axes[1,0].tick_params(axis='x', rotation=30)
df['shipping_type'].value_counts().plot(kind='bar', ax=axes[1,1], color="#b08d57"); axes[1,1].set_title("Hình thức giao hàng"); axes[1,1].tick_params(axis='x', rotation=15)
plt.tight_layout(); plt.show()

print("Churn theo thành viên (%):\n", (churn_by_membership*100).round(1))
print("\nChurn theo giảm giá (%):\n", (churn_by_discount*100).round(1))

# Dashboard: khu vực & sản phẩm
top_provinces = df['province'].value_counts().head(10)
region_spend_share = df.groupby('region')['monetary_est_vnd'].sum()
region_spend_share = region_spend_share / region_spend_share.sum() * 100

fig, axes = plt.subplots(2, 2, figsize=(12, 9))
top_provinces.plot(kind='bar', ax=axes[0,0], color="#8e6b3f"); axes[0,0].set_title("Top 10 tỉnh/thành theo số lượng KH"); axes[0,0].tick_params(axis='x', rotation=45)
region_spend_share.plot(kind='pie', ax=axes[0,1], autopct='%1.1f%%'); axes[0,1].set_ylabel(""); axes[0,1].set_title("Tỷ trọng chi tiêu theo miền")
df['jewelry_category'].value_counts().plot(kind='bar', ax=axes[1,0], color="#a15c38"); axes[1,0].set_title("Danh mục trang sức được mua nhiều nhất"); axes[1,0].tick_params(axis='x', rotation=30)
df['material'].value_counts().plot(kind='bar', ax=axes[1,1], color="#c9a86a"); axes[1,1].set_title("Chất liệu trang sức phổ biến"); axes[1,1].tick_params(axis='x', rotation=30)
plt.tight_layout(); plt.show()

"""6. Phân cụm khách hàng (Clustering)"""

rfm_cols = ['recency_proxy_days', 'previous_purchases', 'monetary_est_vnd', 'clv_est_vnd']
X_rfm = df[rfm_cols].copy()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_rfm)

inertias = []
K_range = range(2, 8)
for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)

plt.figure(figsize=(7, 5))
plt.plot(list(K_range), inertias, marker='o')
plt.xlabel("Số cụm K"); plt.ylabel("Inertia"); plt.title("Biểu đồ Elbow xác định số cụm tối ưu")
plt.show()

K_FINAL = 4
km_final = KMeans(n_clusters=K_FINAL, random_state=42, n_init=10)
df['cluster'] = km_final.fit_predict(X_scaled)

cluster_summary = df.groupby('cluster').agg(
    so_luong=('customer_id', 'count'),
    recency_tb=('recency_proxy_days', 'mean'),
    prev_purchases_tb=('previous_purchases', 'mean'),
    monetary_tb=('monetary_est_vnd', 'mean'),
    clv_tb=('clv_est_vnd', 'mean'),
).round(1)
cluster_summary['ty_le_%'] = (cluster_summary['so_luong'] / len(df) * 100).round(1)

# Gán nhãn nhóm theo đặc điểm: recency cao nhất -> nguy cơ rời bỏ; còn lại xếp theo CLV giảm dần
risk_cluster = cluster_summary['recency_tb'].idxmax()
remaining = [c for c in cluster_summary.index if c != risk_cluster]
remaining_sorted = cluster_summary.loc[remaining].sort_values('clv_tb', ascending=False).index.tolist()
label_map = {risk_cluster: "Khách hàng có nguy cơ rời bỏ"}
tags = ["Khách hàng VIP (giá trị cao nhất)", "Khách hàng trung thành", "Khách hàng phổ thông / mới"]
for c, t in zip(remaining_sorted, tags):
    label_map[c] = t
cluster_summary['nhom'] = cluster_summary.index.map(label_map)
df['cluster_name'] = df['cluster'].map(label_map)

cluster_summary.sort_values('clv_tb', ascending=False)

# Hình 7: phân bố khách hàng theo Previous Purchases & Monetary, tô màu theo cụm
plt.figure(figsize=(8, 6))
sns.scatterplot(data=df, x='previous_purchases', y='monetary_est_vnd', hue='cluster_name', palette="Set2", alpha=0.6, s=25)
plt.ylabel("Monetary ước tính (VND)"); plt.xlabel("Previous Purchases")
plt.title("Phân bố khách hàng theo Previous Purchases và Monetary, tô màu theo cụm")
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout(); plt.show()

# Câu hỏi kinh doanh 2: Top 5 khách hàng có CLV cao nhất
top5_vip = df.sort_values('clv_est_vnd', ascending=False).head(5)[['customer_id','clv_est_vnd','monetary_est_vnd','previous_purchases']]
top5_vip

"""7. Dự báo giá trị khách hàng (Linear Regression)

7.1. Mô hình A — Dự đoán CLV ước tính (`clv_est_vnd`)
"""

featA_num = ['age', 'purchase_amount_vnd', 'previous_purchases', 'review_rating']
featA_cat = ['jewelry_category', 'material', 'discount_applied', 'promo_code_used', 'membership_status', 'has_gemstone']
XA = pd.get_dummies(df[featA_num + featA_cat], columns=featA_cat, drop_first=True)
yA = df['clv_est_vnd']

XA_train, XA_test, yA_train, yA_test = train_test_split(XA, yA, test_size=0.2, random_state=42)
modelA = LinearRegression().fit(XA_train, yA_train)
predA = modelA.predict(XA_test)

r2_A = r2_score(yA_test, predA)
mae_A = mean_absolute_error(yA_test, predA)
print(f"R^2 = {r2_A:.3f}   MAE = {mae_A:,.0f} VND")

coefA = pd.Series(modelA.coef_, index=XA.columns).sort_values(key=abs, ascending=False)
print("\nTop hệ số hồi quy quan trọng nhất:")
print(coefA.head(8).round(0))

plt.figure(figsize=(6, 5.5))
plt.scatter(yA_test/1e6, predA/1e6, alpha=0.4, s=18)
lims = [0, max(yA_test.max(), predA.max())/1e6]
plt.plot(lims, lims, 'r--', linewidth=1)
plt.xlabel("Giá trị thực tế CLV (triệu VND)"); plt.ylabel("Giá trị dự đoán CLV (triệu VND)")
plt.title("So sánh thực tế và dự đoán CLV ước tính")
plt.tight_layout(); plt.show()

"""7.2. Mô hình B — Dự đoán chi tiêu ước tính kỳ tiếp theo (`next_period_spend_est_vnd`)"""

featB_num = ['age', 'purchase_amount_vnd', 'previous_purchases', 'review_rating']
featB_cat = ['jewelry_category', 'occasion', 'discount_applied', 'promo_code_used', 'membership_status']
XB = pd.get_dummies(df[featB_num + featB_cat], columns=featB_cat, drop_first=True)
yB = df['next_period_spend_est_vnd']

XB_train, XB_test, yB_train, yB_test = train_test_split(XB, yB, test_size=0.2, random_state=42)
modelB = LinearRegression().fit(XB_train, yB_train)
predB = modelB.predict(XB_test)

r2_B = r2_score(yB_test, predB)
mae_B = mean_absolute_error(yB_test, predB)
print(f"R^2 = {r2_B:.3f}   MAE = {mae_B:,.0f} VND")

coefB = pd.Series(modelB.coef_, index=XB.columns).sort_values(key=abs, ascending=False)
print("\nTop hệ số hồi quy quan trọng nhất:")
print(coefB.head(8).round(0))

plt.figure(figsize=(6, 5.5))
plt.scatter(yB_test/1e6, predB/1e6, alpha=0.4, s=18, color="#a15c38")
lims = [0, max(yB_test.max(), predB.max())/1e6]
plt.plot(lims, lims, 'r--', linewidth=1)
plt.xlabel("Giá trị thực tế chi tiêu kỳ sau (triệu VND)"); plt.ylabel("Giá trị dự đoán (triệu VND)")
plt.title("So sánh thực tế và dự đoán chi tiêu kỳ tiếp theo")
plt.tight_layout(); plt.show()

"""8. Dự đoán khách hàng rời bỏ (Classification)

"""

featC_num = ['age', 'purchase_amount_vnd', 'previous_purchases', 'review_rating', 'clv_est_vnd']
featC_cat = ['jewelry_category', 'material', 'occasion', 'payment_method', 'shipping_type',
             'discount_applied', 'promo_code_used', 'membership_status', 'gender', 'has_gemstone']
XC = pd.get_dummies(df[featC_num + featC_cat], columns=featC_cat, drop_first=True)
yC = df['churn']

XC_train, XC_test, yC_train, yC_test = train_test_split(XC, yC, test_size=0.2, random_state=42, stratify=yC)
clf = RandomForestClassifier(n_estimators=300, class_weight='balanced', random_state=42, max_depth=8)
clf.fit(XC_train, yC_train)
predC = clf.predict(XC_test)

acc = accuracy_score(yC_test, predC)
prec = precision_score(yC_test, predC)
rec = recall_score(yC_test, predC)
f1 = f1_score(yC_test, predC)
print(f"Accuracy = {acc*100:.1f}%   Precision = {prec*100:.1f}%   Recall = {rec*100:.1f}%   F1 = {f1*100:.1f}%")

cm = confusion_matrix(yC_test, predC)
plt.figure(figsize=(5, 4.5))
sns.heatmap(cm, annot=True, fmt='d', cmap="YlOrBr", xticklabels=['Không rời bỏ','Rời bỏ'], yticklabels=['Không rời bỏ','Rời bỏ'])
plt.xlabel("Dự đoán"); plt.ylabel("Thực tế"); plt.title("Ma trận nhầm lẫn của mô hình dự đoán churn")
plt.tight_layout(); plt.show()

importances = pd.Series(clf.feature_importances_, index=XC.columns).sort_values(ascending=False).head(7)
plt.figure(figsize=(8, 4.5))
importances.sort_values().plot(kind='barh', color="#8e6b3f")
plt.title("Mức độ quan trọng của các biến (Top 7) - Mô hình dự đoán churn")
plt.xlabel("Mức độ quan trọng")
plt.tight_layout(); plt.show()

importances

"""9. Trả lời các câu hỏi kinh doanh"""

df['churn_proba'] = clf.predict_proba(XC)[:, 1]

print("Câu hỏi 1 - Có bao nhiêu nhóm khách hàng khác nhau?")
print(cluster_summary[['so_luong', 'ty_le_%', 'nhom']].sort_values('ty_le_%', ascending=False))

print("\nCâu hỏi 2 - Khách hàng nào có giá trị cao nhất? (Top 5 theo CLV)")
print(top5_vip)

print("\nCâu hỏi 3 - Khách hàng nào có nguy cơ rời bỏ? (Top 5 ưu tiên giữ chân)")
priority = df[df['cluster_name'] == "Khách hàng có nguy cơ rời bỏ"].sort_values('churn_proba', ascending=False).head(5)[
    ['customer_id', 'clv_est_vnd', 'churn_proba', 'previous_purchases', 'review_rating']]
print(priority)

# (Tùy chọn) Xuất file dữ liệu đã xử lý & gắn nhãn cụm/churn để nộp kèm báo cáo
df.to_csv("trang_suc_processed_final.csv", index=False, encoding='utf-8-sig')
from google.colab import files
files.download("trang_suc_processed_final.csv")